package gameRoom;

/**
 *
 * @author Yeray
 */
public class KillerCode extends javax.swing.JFrame {
    
    //variables para eventos
    int[] sequence = {27};
    int currentButton = 0;
    
    /**
     * Creates new form KillerCode
     */
    public KillerCode() {
        initComponents();
        initConf();
    }
    
    /**
     * Settea configuración extra
     */
    private void initConf(){
        this.setLocationRelativeTo(null);
        this.setSize(720, 718);
    }
    
    /**
     * Recibe el codigo de la tecla pulsada y si la secuencia es la que define
     * int[] sequence ocurre el resultado
     * @param keyP 
     */
    public void checkEvent(int keyP) {
    if (keyP == sequence[currentButton]) {
        currentButton ++ ;
    }else{
        currentButton = 0;
    }
    if(currentButton == sequence.length) {
        currentButton = 0;
        this.dispose();
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldExit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameRoom/img/putoMono.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        jTextFieldExit.setText("jTextField1");
        jTextFieldExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldExitKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Recibe el evento de tecla pulsada extrae el código de la tecla 
     * y lo envia al método checkEvent()
     * @param evt 
     */
    private void jTextFieldExitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldExitKeyPressed
        // TODO add your handling code here:
        checkEvent(evt.getKeyCode());
    }//GEN-LAST:event_jTextFieldExitKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KillerCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KillerCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KillerCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KillerCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KillerCode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldExit;
    // End of variables declaration//GEN-END:variables
}
