package gameRoom;

import game.KillerGame;
import sound.KillerSound;

/**
 *
 * @author Yeray
 */
public class KillerPanelWinner extends javax.swing.JPanel {
    //Variable Killer
    private KillerGame kg;
    private KillerRoom kr;
    
    /**
     * Creates new form KillerPanelAjustes
     */
    public KillerPanelWinner(KillerRoom kr) {
        this.kr = kr;
        kg = kr.getKg();
        initComponents();
    }

    /**
     * Recibe la String del nombre del ganador para 
     * mostrarla en un cuadro
     * @param aux 
     */
    public void setWinner(String aux){
        jTextFieldWinner.setText(aux);
    }

    /**
     * Getter del jPanel
     * @return 
     */
    public KillerPanelWinner getKillerPanelAjustes(){
        return this;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelCopy = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jTextFieldWinner = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(525, 525));
        setMinimumSize(new java.awt.Dimension(525, 525));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameRoom/img/winner.png"))); // NOI18N
        jLabelTitulo.setText("jLabel1");
        jLabelTitulo.setPreferredSize(new java.awt.Dimension(480, 80));
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 490, 110));

        jLabelCopy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCopy.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCopy.setText("KillerTeam ®");
        add(jLabelCopy, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, -1, -1));

        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameRoom/img/Volver.png"))); // NOI18N
        jButtonVolver.setBorderPainted(false);
        jButtonVolver.setContentAreaFilled(false);
        jButtonVolver.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonVolver.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gameRoom/img/VolverOscuro.png"))); // NOI18N
        jButtonVolver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gameRoom/img/VolverBrillante.png"))); // NOI18N
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 130, -1));

        jTextFieldWinner.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTextFieldWinner.setForeground(new java.awt.Color(255, 204, 0));
        jTextFieldWinner.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldWinner.setText("Yeray");
        jTextFieldWinner.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        jTextFieldWinner.setDisabledTextColor(new java.awt.Color(255, 204, 0));
        jTextFieldWinner.setEnabled(false);
        jTextFieldWinner.setOpaque(false);
        add(jTextFieldWinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 490, 80));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameRoom/img/stars.gif"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento del botón Volver al menú principal
     * @param evt 
     */
    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // VOLVER
        kg.startSound(KillerSound.ClipType.PC_CLICK);
        kr.setKillerPanelPrincipal();
        //kg.resetGame();
    }//GEN-LAST:event_jButtonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelCopy;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldWinner;
    // End of variables declaration//GEN-END:variables
}
