/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameRoom;

import game.KillerGame;
import java.awt.Color;

/**
 *
 * @author Yeray
 */
public class KillerPanelPrincipal extends javax.swing.JPanel {
    //Variable Killer Game
    private KillerGame kg;
    
    //getKillerShips()  para la lista
    
    /**
     * Creates new form KillerPanelPrincipal
     * @param kg
     */
    public KillerPanelPrincipal(KillerGame kg) {
        this.kg = kg;
        initComponents();
        jButtonJugar.setEnabled(true);

    }
    
    public void setFeedbackConnetionLeft(Boolean aux){
        if(aux == true){
         jLabelConFeedackL.setForeground(Color.GREEN);
         jLabelConFeedackL.setText("CONECTADO");
    }else{
         jLabelConFeedackL.setForeground(Color.RED);
         jLabelConFeedackL.setText("DESCONECTADO");
        }
    }
    
    public void setFeedbackConnetionRight(Boolean aux){
        if(aux == true){
         jLabelConFeedackR.setForeground(Color.GREEN);
         jLabelConFeedackL.setText("CONECTADO");
    }else{
         jLabelConFeedackR.setForeground(Color.RED);
         jLabelConFeedackL.setText("DESCONECTADO");
        }
    }
    
    public KillerPanelPrincipal getKillerPanelPrincipal(){
        return this;
    }
    
    public KillerGame getKg(){
        return this.kg;
    }
    
    public void setButtonPlay(Boolean aux){
        if (aux == true) {
            jButtonJugar.setEnabled(true);
        } else {
            jButtonJugar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelCopy = new javax.swing.JLabel();
        jButtonJugar = new javax.swing.JButton();
        jButtonConectar = new javax.swing.JButton();
        jButtonAjustes = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelConFeedackL = new javax.swing.JLabel();
        jLabelConFeedackR = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(525, 525));
        setMinimumSize(new java.awt.Dimension(525, 525));
        setPreferredSize(new java.awt.Dimension(525, 525));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameRoom/img/Logo.png"))); // NOI18N
        jLabelTitulo.setText("jLabel1");
        jLabelTitulo.setPreferredSize(new java.awt.Dimension(480, 80));
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabelCopy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCopy.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCopy.setText("KillerTeam ®");
        add(jLabelCopy, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, -1, -1));

        jButtonJugar.setText("JUGAR");
        jButtonJugar.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        add(jButtonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jButtonConectar.setText("CONECTAR");
        jButtonConectar.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarActionPerformed(evt);
            }
        });
        add(jButtonConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jButtonAjustes.setText("AJUSTES");
        jButtonAjustes.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjustesActionPerformed(evt);
            }
        });
        add(jButtonAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        jButtonSalir.setText("SALIR");
        jButtonSalir.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jLabelConFeedackL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelConFeedackL.setForeground(new java.awt.Color(255, 0, 0));
        jLabelConFeedackL.setText("DESCONECTADO");
        add(jLabelConFeedackL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabelConFeedackR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelConFeedackR.setForeground(new java.awt.Color(255, 0, 0));
        jLabelConFeedackR.setText("DESCONECTADO");
        add(jLabelConFeedackR, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameRoom/img/stars.gif"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // SALIR
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjustesActionPerformed
        // AJUSTES
        kg.setKillerPanelAjustes();
    }//GEN-LAST:event_jButtonAjustesActionPerformed

    private void jButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarActionPerformed
        // CONECTAR
        kg.setKillerPanelConectar();
    }//GEN-LAST:event_jButtonConectarActionPerformed

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        // JUGAR
        kg.sendStart();
    }//GEN-LAST:event_jButtonJugarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjustes;
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelConFeedackL;
    private javax.swing.JLabel jLabelConFeedackR;
    private javax.swing.JLabel jLabelCopy;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
